{% set python_min = '3.10.0' %}
{% set name = "pyDGSA" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydgsa-{{ version }}.tar.gz
  sha256: 0307f50bc595833832a8de2c1ed038dc95c042bfed6bd849495f85e1a3bfc29b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - numpy >=2.0.0,<3.0.0
    - matplotlib-base >=3.7.0,<4.0.0
    - pandas >=2.2.2,<3.0.0
    - tqdm >=4.66.4,<5.0.0
    - scikit-learn >=1.5.1,<2.0.0
    - scipy >=1.14.0,<2.0.0

test:
  imports:
    - pyDGSA
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pyDGSA/
  summary: Python implementation of distance-based generalized sensitivity analysis (DGSA)
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zperzan
