{% set name = "pyDGSA" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydgsa-{{ version }}.tar.gz
  sha256: b6393f1bd38014d07b12f88ff6aab28f897d234acea6e02df3fc3bfbdd0ac9d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - numpy >=2.0.0,<3.0.0
    - matplotlib-base >=3.7.0,<4.0.0
    - pandas >=2.2.2,<3.0.0
    - tqdm >=4.66.4,<5.0.0
    - scikit-learn >=1.5.1,<2.0.0
    - scipy >=1.14.0,<2.0.0
    - ipywidgets >=8.1.3,<9.0.0
    - pytest >=8.3.4,<9.0.0

test:
  imports:
    - pyDGSA
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pyDGSA/
  summary: Python implementation of distance-based generalized sensitivity analysis (DGSA)
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zperzan
